# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

# Run everything on the `android` queue
agents:
  queue: android

steps:
  - label: "Gradle Wrapper Validation"
    command: |
      validate_gradle_wrapper
    plugins: [$CI_TOOLKIT]

  # Wait for Gradle Wrapper to be validated before running any other jobs
  - wait

  - label: "Lint"
    key: "lint"
    command: .buildkite/commands/lint.sh
    plugins: [$CI_TOOLKIT]
    artifact_paths:
      - "aztec/build/reports/*"

  - label: "Unit Tests"
    key: "test"
    command: .buildkite/commands/unit-test.sh
    plugins: [$CI_TOOLKIT]
    artifact_paths:
      - "aztec/build/test-results/**/*.xml"

  - label: "Connected Tests"
    key: "connected-test"
    command: .buildkite/commands/connected-tests.sh
    plugins: [$CI_TOOLKIT]
    artifact_paths:
      - "aztec/build/test-results/**/*.xml"

  - label: "Publish :aztec"
    key: "publish-aztec"
    command: .buildkite/commands/publish-aztec.sh
    plugins: [$CI_TOOLKIT]

  - label: "Publish :glide-loader"
    key: "publish-glide-loader"
    depends_on:
      - "publish-aztec"
    command: .buildkite/commands/publish-glide-loader.sh
    plugins: [$CI_TOOLKIT]

  - label: "Publish :picasso-loader"
    key: "publish-picasso-loader"
    depends_on:
      - "publish-aztec"
    command: .buildkite/commands/publish-picasso-loader.sh
    plugins: [$CI_TOOLKIT]

  - label: "Publish :wordpress-shortcodes"
    key: "publish-wordpress-shortcodes"
    depends_on:
      - "publish-aztec"
    command: .buildkite/commands/publish-wordpress-shortcodes.sh
    plugins: [$CI_TOOLKIT]

  - label: "Publish :wordpress-comments"
    key: "publish-wordpress-comments"
    depends_on:
      - "publish-aztec"
    command: .buildkite/commands/publish-wordpress-comments.sh
    plugins: [$CI_TOOLKIT]

  - label: "Publish :media-placeholders"
    key: "publish-media-placeholders"
    depends_on:
      - "publish-aztec"
    command: .buildkite/commands/publish-media-placeholders.sh
    plugins: [$CI_TOOLKIT]
