# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

# Run everything on the `android` queue
agents:
  queue: android

steps:
  - label: "dependency analysis"
    command: |
      echo "--- 📊 Analyzing"
      ./gradlew buildHealth
    plugins: [$CI_TOOLKIT]
    artifact_paths:
      - "build/reports/dependency-analysis/build-health-report.*"
    notify:
      - slack: "#android-core-notifs"
        if: build.state == "failed"
